import { useState } from "react";
import { useNavigate } from "react-router-dom";
import HotelNavbar from "../components/HotelNavbar";
import HotelFooter from "../components/HotelFooter";
import { authRepository } from "../repositories/authRepository";
import "./ReviewsPage.css";

type Review={id:string;name:string;rating:number;text:string;date:string};
const KEY="hotel-rolex-reviews";
const initial:Review[]=[{id:"1",name:"Carlos M.",rating:5,text:"Excelente atención y habitaciones muy cómodas.",date:"2026-08-12"},{id:"2",name:"Sofía R.",rating:4,text:"Muy buena experiencia y espacios agradables.",date:"2026-08-20"},{id:"3",name:"Daniel P.",rating:5,text:"La reserva fue sencilla y el servicio excelente.",date:"2026-09-01"}];
function getReviews():Review[]{try{return JSON.parse(localStorage.getItem(KEY)||"null")||initial}catch{return initial}}
function ReviewsPage(){const navigate=useNavigate();const user=authRepository.getCurrentUser();const [reviews,setReviews]=useState(getReviews());const [rating,setRating]=useState(5);const [text,setText]=useState("");const [notice,setNotice]=useState("");const avg=reviews.length?reviews.reduce((a,r)=>a+r.rating,0)/reviews.length:0;const submit=(e:React.FormEvent)=>{e.preventDefault();if(!user){navigate("/login?redirect=/opiniones");return}if(!text.trim())return;const item={id:String(Date.now()),name:user.name,rating,text:text.trim(),date:new Date().toISOString().slice(0,10)};const next=[item,...reviews];localStorage.setItem(KEY,JSON.stringify(next));setReviews(next);setText("");setNotice("¡Gracias por compartir tu experiencia!");};return <main className="reviews-page"><HotelNavbar/><header className="reviews-hero"><span>HOTEL ROLEX · EXPERIENCIAS</span><h1>Opiniones de nuestros huéspedes.</h1><p>Conoce experiencias reales y comparte la tuya después de tu estancia.</p><div className="reviews-score"><strong>{avg.toFixed(1)}</strong><span>★★★★★</span><small>{reviews.length} opiniones registradas</small></div></header><section className="reviews-content"><div className="review-form-card"><span>COMPARTE TU EXPERIENCIA</span><h2>¿Cómo fue tu estancia?</h2>{!user?<button onClick={()=>navigate("/login?redirect=/opiniones")}>Inicia sesión para opinar →</button>:<form onSubmit={submit}><label>Calificación<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="5">★★★★★ Excelente</option><option value="4">★★★★ Muy buena</option><option value="3">★★★ Buena</option><option value="2">★★ Regular</option><option value="1">★ Necesita mejorar</option></select></label><label>Comentario<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={240} placeholder="Cuéntanos cómo fue tu experiencia..." required/></label>{notice&&<div className="review-notice">✓ {notice}</div>}<button>Publicar opinión →</button></form>}</div><div className="review-list">{reviews.map(r=><article key={r.id}><div className="review-top"><strong>{r.name}</strong><span>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span></div><p>“{r.text}”</p><small>{r.date}</small></article>)}</div></section><HotelFooter/></main>}
export default ReviewsPage;
