import { useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { cancelReservation, getReservations } from "../../data/rooms";
import { authRepository } from "../../repositories/authRepository";
import { getEffectiveRooms, getHotelStats, setRoomStatus, updatePaymentStatus, updateReservationStatus } from "../../services/hotelService";
import "./AdminDashboardPage.css";

function AdminDashboardPage(){const navigate=useNavigate();const user=authRepository.getCurrentUser();const [refresh,setRefresh]=useState(0);const [tab,setTab]=useState("resumen");const [calendarDate,setCalendarDate]=useState(new Date().toISOString().slice(0,7));const stats=useMemo(()=>getHotelStats(),[refresh]);const rooms=useMemo(()=>getEffectiveRooms(),[refresh]);const reservations=useMemo(()=>getReservations(),[refresh]);
if(!user)return <Navigate to="/login?redirect=/admin" replace/>;if(user.role!=="ADMIN")return <main className="admin-denied"><h1>Acceso restringido</h1><p>Esta sección es exclusiva para administradores.</p><button onClick={()=>navigate("/")}>Volver al inicio</button></main>;
const refreshData=()=>setRefresh(v=>v+1);const active=reservations.filter(r=>r.status!=="Cancelada");const monthReservations=active.filter(r=>r.checkIn.startsWith(calendarDate)||r.checkOut.startsWith(calendarDate));const confirmCancel=(id:string)=>{updateReservationStatus(id,"Cancelada");refreshData()};return <main className="admin-page"><header className="admin-header"><div><span>HOTEL ROLEX · ADMINISTRACIÓN</span><h1>Panel de control.</h1><p>Gestiona habitaciones, reservas, huéspedes, pagos y operación diaria.</p></div><div className="admin-head-actions"><button onClick={()=>navigate("/")}>Ver sitio</button><button onClick={()=>{authRepository.logout();navigate("/",{replace:true})}}>Cerrar sesión</button></div></header><nav className="admin-tabs">{[["resumen","Resumen"],["reservas","Reservas"],["calendario","Calendario"],["habitaciones","Habitaciones"],["pagos","Pagos"],["operacion","Check-in / Check-out"],["usuarios","Huéspedes"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav><section className="admin-content">
{tab==="resumen"&&<><div className="admin-stats"><div><b>HABITACIONES</b><strong>{stats.rooms}</strong><span>Inventario total</span></div><div><b>DISPONIBLES</b><strong>{stats.available}</strong><span>Listas para reservar</span></div><div><b>OCUPADAS</b><strong>{stats.occupied}</strong><span>En uso</span></div><div><b>MANTENIMIENTO</b><strong>{stats.maintenance}</strong><span>Fuera de servicio</span></div><div><b>RESERVAS</b><strong>{stats.reservations}</strong><span>Activas</span></div><div><b>INGRESOS</b><strong>${stats.revenue}</strong><span>Pagos registrados</span></div></div><div className="admin-panels"><article><span>ESTADO OPERATIVO</span><h2>Resumen del hotel</h2><div className="bars"><p><b>Disponibilidad</b><i style={{width:`${stats.rooms?stats.available/stats.rooms*100:0}%`}}></i><small>{stats.available}/{stats.rooms}</small></p><p><b>Pagos completados</b><i style={{width:`${active.length?stats.paid/active.length*100:0}%`}}></i><small>{stats.paid}/{active.length}</small></p><p><b>Pagos pendientes</b><i style={{width:`${active.length?stats.pending/active.length*100:0}%`}}></i><small>{stats.pending}</small></p></div></article><article><span>ACCIONES RÁPIDAS</span><h2>Operación</h2><div className="quick-actions"><button onClick={()=>setTab("reservas")}>Ver reservas →</button><button onClick={()=>setTab("pagos")}>Revisar pagos →</button><button onClick={()=>setTab("habitaciones")}>Gestionar habitaciones →</button><button onClick={()=>setTab("calendario")}>Abrir calendario →</button></div></article></div></>}
{tab==="reservas"&&<AdminTable title="Todas las reservas" reservations={reservations} onRefresh={refreshData} onCancel={confirmCancel} />}
{tab==="calendario"&&<section className="admin-section"><div className="admin-section-head"><div><span>PLANIFICACIÓN</span><h2>Calendario de ocupación</h2></div><input type="month" value={calendarDate} onChange={e=>setCalendarDate(e.target.value)}/></div><div className="calendar-grid"><div className="calendar-label">Habitación</div>{[1,2,3,4,5,6,7].map(d=><div className="calendar-day" key={d}>{d}</div>)}{rooms.map(room=><div className="calendar-row" key={room.number}><strong>#{room.number}</strong>{[1,2,3,4,5,6,7].map(d=>{const cell=`${calendarDate}-${String(d).padStart(2,"0")}`;const booked=monthReservations.some(r=>r.roomNumber===room.number&&r.checkIn<=cell&&r.checkOut>cell);return <span className={booked?"booked":room.status!=="Disponible"?"blocked":"free"} key={d}>{booked?"R":""}</span>})}</div>)}</div><p className="legend"><span className="free"></span> Disponible <span className="booked"></span> Reserva <span className="blocked"></span> Estado no disponible</p></section>}
{tab==="habitaciones"&&<section className="admin-section"><div className="admin-section-head"><div><span>INVENTARIO</span><h2>Gestionar habitaciones</h2></div></div><div className="admin-room-grid">{rooms.map(room=><article key={room.number}><div><span>#{room.number}</span><b>{room.type}</b></div><p>{room.capacity} huéspedes · ${room.price}/noche</p><strong className={`admin-room-status ${room.status}`}>{room.status}</strong><select value={room.status} onChange={e=>{setRoomStatus(room.number,e.target.value as any);refreshData()}}><option>Disponible</option><option>Ocupada</option><option>Mantenimiento</option></select></article>)}</div></section>}
{tab==="pagos"&&<AdminTable title="Control de pagos" reservations={active} paymentMode onRefresh={refreshData} onCancel={confirmCancel} />}
{tab==="operacion"&&<section className="admin-section"><div className="admin-section-head"><div><span>RECEPCIÓN</span><h2>Check-in / Check-out</h2></div></div><div className="operation-list">{active.map(r=><article key={r.id}><div><small>{r.id}</small><strong>Habitación #{r.roomNumber}</strong><span>{r.guestName} · {r.checkIn} → {r.checkOut}</span></div><div><b>{r.paymentStatus||"Pendiente"}</b><button onClick={()=>window.print()}>Comprobante</button><button onClick={()=>confirmCancel(r.id)}>Check-out / liberar</button></div></article>)}</div></section>}
{tab==="usuarios"&&<section className="admin-section"><div className="admin-section-head"><div><span>HUÉSPEDES</span><h2>Usuarios registrados</h2></div></div><div className="user-list">{authRepository.getUsers().map(u=><article key={u.id}><strong>{u.name}</strong><span>{u.carnet}</span><b>{u.role}</b></article>)}</div></section>}
</section></main>}
function AdminTable({title,reservations,paymentMode,onRefresh,onCancel}:{title:string;reservations:any[];paymentMode?:boolean;onRefresh:()=>void;onCancel:(id:string)=>void}){return <section className="admin-section"><div className="admin-section-head"><div><span>GESTIÓN</span><h2>{title}</h2></div></div><div className="admin-table">{reservations.map(r=><article key={r.id}><div><small>{r.id}</small><strong>#{r.roomNumber} · {r.guestName}</strong><span>{r.checkIn} → {r.checkOut} · {r.guests} huéspedes</span></div><div><b>${r.total}</b><span>{r.paymentMethod||"No especificado"}</span><em className={r.paymentStatus}>{r.paymentStatus||"Pendiente"}</em></div><div>{paymentMode&&r.paymentStatus!=="Pagado"&&<button onClick={()=>{updatePaymentStatus(r.id,"Pagado");onRefresh()}}>Confirmar pago</button>}{!paymentMode&&r.status!=="Cancelada"&&<button onClick={()=>onCancel(r.id)}>Cancelar</button>}{r.status==="Cancelada"&&<em>Cancelada</em>}</div></article>)}</div></section>}
export default AdminDashboardPage;
